dnsWildCard: "example.com"

# -- Specifies a Pod template to use as the basis for the configuration of the Pod that executes each Task.
podTemplate: []
# nodeSelector:
#   disktype: ssd
# tolerations:
#   - key: "key"
#     operator: "Equal"
#     value: "value"
#     effect: "NoSchedule"
