apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  labels:
    # -- Required label to identify the pipeline type as "review".
    app.edp.epam.com/pipelinetype: review
    app.edp.epam.com/triggertemplate: github-review-template
    {{- include "edp-tekton.labels" . | nindent 4 }}
  name: github-review
spec:
  description: The Review pipeline template for validating changes from Github repositories.
    This template also demonstrates how to extend the pipeline with custom tasks, including the custom task "hello-world".

  # -- Parameters for the pipeline, automatically injected by the Tekton Trigger Template.
  params:
    - default: https://portal-{{ $.Release.Namespace }}.{{ $.Values.dnsWildCard }}/c/main/pipelines/$(context.pipelineRun.namespace)/$(context.pipelineRun.name)
      name: pipelineUrl
      type: string
    - default: https://github.com/epmd-edp/python-python-python-3.8
      description: git url to clone
      name: git-source-url
      type: string
    - default: master
      description: git revision to checkout (branch, tag, sha, ref…)
      name: git-source-revision
      type: string
    - default: ''
      description: Refspec to fetch before checking out revision.
      name: git-refspec
      type: string
    - default: ''
      description: Target branch of Merge Request
      name: targetBranch
      type: string
    - default: ''
      description: Change number from Merge Request
      name: changeNumber
      type: string
    - default: python-app
      description: Project name
      name: CODEBASE_NAME
      type: string
    - description: Codebasebranch name
      name: CODEBASEBRANCH_NAME
      type: string
    - description: repository full name
      name: gitfullrepositoryname
      type: string
    - description: commit sha
      name: gitsha
      type: string

    # -- Example of custom parameters that may be utilized within Tekton tasks.
    - default: "World"
      description: "Example parameter"
      name: username
      type: string
    - default: 'alpine:3.18.9'
      name: image-version
      type: string
  tasks:
    - name: github-set-pending-status
      params:
        - name: REPO_FULL_NAME
          value: $(params.gitfullrepositoryname)
        - name: DESCRIPTION
          value: Build has started
        - name: STATE
          value: pending
        - name: AUTH_TYPE
          value: Token
        - name: GITHUB_TOKEN_SECRET_NAME
          value: ci-github
        - name: GITHUB_TOKEN_SECRET_KEY
          value: token
        - name: SHA
          value: $(params.gitsha)
        - name: TARGET_URL
          value: $(params.pipelineUrl)
      taskRef:
        kind: Task
        name: github-set-status
    - name: fetch-repository
      params:
        - name: url
          value: $(params.git-source-url)
        - name: revision
          value: $(params.git-source-revision)
        - name: refspec
          value: $(params.git-refspec)
        - name: subdirectory
          value: source
      runAfter:
        - github-set-pending-status
      taskRef:
        kind: Task
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
        - name: ssh-directory
          workspace: ssh-creds
    - name: init-values
      params:
        - name: CODEBASE_NAME
          value: $(params.CODEBASE_NAME)
        - name: BRANCH_NAME
          value: $(params.git-source-revision)
      runAfter:
        - fetch-repository
      taskRef:
        kind: Task
        name: init-values

    # -- Example of a custom task added to the pipeline.
    # This task demonstrates how to include custom tasks in the pipeline.
    # It can be adapted to meet specific requirements by modifying or adding custom logic.
    - name: hello-world
      taskRef:
        name: hello-world
      runAfter:
      - init-values
      params:
      - name: BASE_IMAGE
        value: "$(params.image-version)"
      - name: username
        value: "$(params.username)"
      workspaces:
        - name: source
          workspace: shared-workspace
          subPath: source
  workspaces:
    - name: shared-workspace
    - name: ssh-creds
  finally:
    - name: github-set-success-status
      params:
        - name: REPO_FULL_NAME
          value: $(params.gitfullrepositoryname)
        - name: DESCRIPTION
          value: Build was successful
        - name: STATE
          value: success
        - name: AUTH_TYPE
          value: Token
        - name: GITHUB_TOKEN_SECRET_NAME
          value: ci-github
        - name: GITHUB_TOKEN_SECRET_KEY
          value: token
        - name: SHA
          value: $(params.gitsha)
        - name: TARGET_URL
          value: $(params.pipelineUrl)
      taskRef:
        kind: Task
        name: github-set-status
      when:
        - input: $(tasks.status)
          operator: in
          values:
            - Succeeded
    - name: github-set-failure-status
      params:
        - name: REPO_FULL_NAME
          value: $(params.gitfullrepositoryname)
        - name: DESCRIPTION
          value: Build has failed
        - name: STATE
          value: failure
        - name: AUTH_TYPE
          value: Token
        - name: GITHUB_TOKEN_SECRET_NAME
          value: ci-github
        - name: GITHUB_TOKEN_SECRET_KEY
          value: token
        - name: SHA
          value: $(params.gitsha)
        - name: TARGET_URL
          value: $(params.pipelineUrl)
      taskRef:
        kind: Task
        name: github-set-status
      when:
        - input: $(tasks.status)
          operator: in
          values:
            - Failed
